name: build

on:
  push:
    branches:
    - master
    paths:
    - "**.R"
    - README.Rmd
    - DESCRIPTION
    - NAMESPACE
    - man/

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e "install.packages(c('rmarkdown', 'styler','usethis', 'devtools', 'covr', 'pkgdown', 'rcmdcheck', 'remotes', 'fs'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Configure git
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
      - name: Style
        run: |
          git status
          Rscript -e 'usethis::use_tidy_style()'
          git add .
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '🎨 Style R code' || echo "No changes to commit"
      - name: Document
        run: |
          Rscript -e "devtools::document()"
          git add man/ NAMESPACE
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '📚 Render Roxygen documentation' || echo "No changes to commit"
      - name: Render README
        run: |
          Rscript -e 'rmarkdown::render("README.Rmd")'
          git add README.md
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '📄 Render README.Rmd' || echo "No changes to commit"
      - name: Docs
        run: |
          Rscript -e "devtools::build_site()"
          git add docs
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m "📑 Build docs site" || echo "No changes to commit"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
